apiVersion: v1
kind: Service
metadata:
  name: flask-sso-service
spec:
  selector:
    app: flask-sso-app
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-sso-app
spec:
  selector:
    matchLabels:
      app: flask-sso-app
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-sso-app
    spec:
      containers:
        - name: flask-sso-app
          image: docker.io/vethusonamit/assignment2devsecops
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000